// Generated by CoffeeScript 1.9.3
(function() {
  chrome.runtime.onMessage.addListener(function(request, sender) {
    return chrome.tabs.create({
      url: request.url
    });
  });

}).call(this);
