// Generated by CoffeeScript 1.9.3
(function() {
  (function($) {
    var nytKey, setStorage;
    nytKey = "f3c37edfcd099580533c530e36e47ed2:17:72571087";
    $(window).bind("keydown", "meta+e", function(e) {
      $.getJSON("https://api.nytimes.com/svc/topstories/v1/home.json?api-key=" + nytKey, function(response) {
        return chrome.storage.local.get({
          visited: []
        }, function(object) {
          var entry, i, len, ref, results, url, visited;
          if (chrome.runtime.lastError) {
            return window.alert("getStorage ERROR! => " + chrome.runtime.lastError);
          } else {
            visited = object.visited;
            ref = response.results;
            results = [];
            for (i = 0, len = ref.length; i < len; i++) {
              entry = ref[i];
              url = entry.url;
              if ($.inArray(url, visited) === -1) {
                visited.push(url);
                setStorage(visited);
                chrome.runtime.sendMessage({
                  url: url
                });
                break;
              } else {
                results.push(void 0);
              }
            }
            return results;
          }
        });
      });
      return false;
    });
    $(window).bind("keydown", "ctrl+e", function(e) {
      chrome.storage.local.remove("visited", function() {
        if (chrome.runtime.lastError) {
          return window.alert("remove ERROR! => " + chrome.runtime.lastError);
        } else {
          return window.alert("Removed \"visited\" from local storage");
        }
      });
      return false;
    });
    return setStorage = function(data) {
      return chrome.storage.local.set({
        visited: data
      }, function() {
        if (chrome.runtime.lastError) {
          return window.alert("setStorage ERROR! => " + chrome.runtime.lastError);
        }
      });
    };
  })(jQuery);

}).call(this);
